DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS
(
    ID   BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) UNIQUE
);
CREATE TABLE GENRES
(
    ID   BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) UNIQUE
);
CREATE TABLE BOOKS
(
    ID        BIGINT PRIMARY KEY AUTO_INCREMENT,
    TITLE     VARCHAR(255),
    AUTHOR_ID BIGINT REFERENCES AUTHORS (ID),
    GENRE_ID  BIGINT REFERENCES GENRES (ID)
);
