spring:
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
  h2:
    console:
      enabled: true
  data:
    mongodb:
      database: library
mongock:
  #runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - org.library.mongock.changelog
